### ISSUE TITLE
Add ability to not disable "press key to stop autoboot"

### ISSUE THREAD

**Issue by lifeeth** [resin-os/resin-beaglebone#46] opened 2016-10-10 14:02 UTC
We need to have the ability to disable this option so that any peripheral connected on the serial port or noise will not stop the boot process.

**Comment by agherzan** [comment] 2016-10-12 23:16
Duplicate of https://github.com/resin-os/resin-beaglebone/issues/39

**Closed by agherzan** 2016-10-12 23:17 UTC
Labels: close/duplicate
